name: jivhala_motors
description: "Jivhala Motors - Vehicle Management Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3

  # Local Storage
  shared_preferences: ^2.2.2

  # HTTP & Networking
  dio: ^5.4.0
  http: ^1.1.2
  http_parser: ^4.0.2

  # Image & File handling
  image_picker: ^1.0.4
  path_provider: ^2.1.1

  # PDF & Printing
  pdf: ^3.10.7
  printing: ^5.11.1

  # Charts
  fl_chart: ^0.65.0

  # Date & Time
  intl: ^0.19.0
  timezone: ^0.10.1

  # Form validation
  email_validator: ^2.1.17

  # Loading & Progress
  loading_animation_widget: ^1.2.0+4

  # Image display & caching
  cached_network_image: ^3.3.1

  # Permission handling
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/image 1 (1).png
    - assets/Group 1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-assets

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# App Icon Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/image 1 (1).png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/image 1 (1).png"
    background_color: "#1976D2"
    theme_color: "#1976D2"
  windows:
    generate: true
    image_path: "assets/image 1 (1).png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/image 1 (1).png"
